name: CI

on:
  # pull_request:
  #   branches:
  #     - '*'
  # push:
  #   branches:
  #     - master
  #     - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  debug:
    name: job-${{ matrix.runson }}
    runs-on: ${{matrix.runson}}
    strategy:
      matrix:
        # runson: [ubuntu-latest,actuated-4cpu-8gb]
        runson: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Configure buildx
      uses: docker/setup-buildx-action@v3
      with:
        cache-binary: true
    - uses: self-actuated/connect-ssh@master

